server:
  port: 9002
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: 123456789
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      .hibernate.default_schema: public
      .hibernate.jdbc.lob.non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
      .naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  application:
    name: USER-SERVICE
  cloud:
    config:
      enabled: true
      uri: http://loacalhost:9296

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

